"""add status column

Revision ID: 2e222a63103a
Revises: 001_initial
Create Date: 2026-07-02 18:08:23.055223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e222a63103a'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('customers', sa.Column('total_spend', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'total_spend')
    op.drop_column('customers', 'status')
    # ### end Alembic commands ###
