"""describe your changes

Revision ID: 56be81fe89b0
Revises: e3e6dac8ae04
Create Date: 2026-07-24 13:22:57.019243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56be81fe89b0'
down_revision: Union[str, None] = 'e3e6dac8ae04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_communications_id'), 'customer_communications', ['id'], unique=False)
    op.alter_column('customer_feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_feedback', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_feedback_invoice'), 'customer_feedback', type_='foreignkey')
    op.drop_constraint(op.f('fk_feedback_customer'), 'customer_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'customer_feedback', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'customer_feedback', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('customer_notes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_notes', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_customer_notes_id'), 'customer_notes', ['id'], unique=False)
    op.alter_column('customer_referrals', 'reward_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('customer_referrals', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_referrals', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('customer_wallets', 'current_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('customer_wallets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_wallets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'customer_wallets', ['customer_id'])
    op.drop_constraint(op.f('fk_wallet_customer'), 'customer_wallets', type_='foreignkey')
    op.create_foreign_key(None, 'customer_wallets', 'customers', ['customer_id'], ['id'])
    op.alter_column('loyalty_points', 'points_earned',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('loyalty_points', 'points_redeemed',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('loyalty_points', 'balance_points',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('loyalty_points', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loyalty_points', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_wallet_transaction'), 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_transactions', 'customer_wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_wallet_transaction'), 'wallet_transactions', 'customer_wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loyalty_points', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('loyalty_points', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loyalty_points', 'balance_points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('loyalty_points', 'points_redeemed',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('loyalty_points', 'points_earned',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'customer_wallets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_wallet_customer'), 'customer_wallets', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'customer_wallets', type_='unique')
    op.alter_column('customer_wallets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('customer_wallets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_wallets', 'current_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('customer_referrals', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('customer_referrals', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customer_referrals', 'reward_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_index(op.f('ix_customer_notes_id'), table_name='customer_notes')
    op.alter_column('customer_notes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('customer_notes', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'customer_feedback', type_='foreignkey')
    op.drop_constraint(None, 'customer_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('fk_feedback_customer'), 'customer_feedback', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_feedback_invoice'), 'customer_feedback', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.alter_column('customer_feedback', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('customer_feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_customer_communications_id'), table_name='customer_communications')
    # ### end Alembic commands ###
