"""make warehouse code unique

Revision ID: 5d5148c6eff3
Revises: 9764dd66e682
Create Date: 2026-08-11 18:37:57.472019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5148c6eff3'
down_revision: Union[str, None] = '9764dd66e682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    # ### end Alembic commands ###
