"""add is_active to suppliers

Revision ID: 85d54ffbe4d6
Revises: 75d06fba5b2e
Create Date: 2026-07-22 21:48:51.619485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d54ffbe4d6'
down_revision: Union[str, None] = '75d06fba5b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("1")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_active')
    # ### end Alembic commands ###
