"""add order returns

Revision ID: 8b2484f5e3a5
Revises: b1ec1b5d716c
Create Date: 2026-08-25 11:47:59.905973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2484f5e3a5'
down_revision: Union[str, None] = 'b1ec1b5d716c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_returns_customer_id'), 'order_returns', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_returns_order_id'), 'order_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_returns_status'), 'order_returns', ['status'], unique=False)
    op.create_index(op.f('ix_order_returns_tenant_id'), 'order_returns', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_returns_tenant_id'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_status'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_order_id'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_customer_id'), table_name='order_returns')
    op.drop_table('order_returns')
    # ### end Alembic commands ###
