"""update supplier phone and gstin length

Revision ID: b1ec1b5d716c
Revises: 5eb4e0af7c61
Create Date: 2026-08-23 22:20:12.013767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1ec1b5d716c'
down_revision: Union[str, None] = '5eb4e0af7c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.alter_column('suppliers', 'gstin',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'gstin',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
