"""add GRN tables

Revision ID: bc131c6e1e4d
Revises: caa6af7fced5
Create Date: 2026-08-15 15:03:26.333766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc131c6e1e4d'
down_revision: Union[str, None] = 'caa6af7fced5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('grn_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grns_grn_number'), 'grns', ['grn_number'], unique=True)
    op.create_index(op.f('ix_grns_purchase_order_id'), 'grns', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_grns_tenant_id'), 'grns', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_grns_warehouse_id'), 'grns', ['warehouse_id'], unique=False)
    op.create_table('grn_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_items_grn_id'), 'grn_items', ['grn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grn_items_grn_id'), table_name='grn_items')
    op.drop_table('grn_items')
    op.drop_index(op.f('ix_grns_warehouse_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_tenant_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_purchase_order_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_grn_number'), table_name='grns')
    op.drop_table('grns')
    # ### end Alembic commands ###
