"""empty message

Revision ID: c070896d644a
Revises: a5d85bdc91e0
Create Date: 2026-09-23 11:12:36.205800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c070896d644a'
down_revision: Union[str, None] = 'a5d85bdc91e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_targets_id'), 'store_targets', ['id'], unique=False)
    op.create_index(op.f('ix_store_targets_store_id'), 'store_targets', ['store_id'], unique=False)
    op.alter_column('delivery_methods', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('delivery_zones', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_payment_gateways_status'), 'payment_gateways', ['status'], unique=False)
    op.create_index(op.f('ix_payment_splits_transaction_id'), 'payment_splits', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_webhook_logs_status'), 'payment_webhook_logs', ['status'], unique=False)
    op.create_index(op.f('ix_payment_webhook_logs_transaction_id'), 'payment_webhook_logs', ['transaction_id'], unique=False)
    op.alter_column('payments', 'gateway_response',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.alter_column('products', 'mrp',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_settlements_gateway_id'), 'settlements', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_store_expenses_id'), 'store_expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_expenses_id'), table_name='store_expenses')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_gateway_id'), table_name='settlements')
    op.alter_column('refunds', 'refund_status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)
    op.alter_column('products', 'mrp',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.alter_column('payments', 'gateway_response',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_webhook_logs_transaction_id'), table_name='payment_webhook_logs')
    op.drop_index(op.f('ix_payment_webhook_logs_status'), table_name='payment_webhook_logs')
    op.drop_index(op.f('ix_payment_splits_transaction_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_gateways_status'), table_name='payment_gateways')
    op.alter_column('delivery_zones', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('delivery_methods', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_store_targets_store_id'), table_name='store_targets')
    op.drop_index(op.f('ix_store_targets_id'), table_name='store_targets')
    op.drop_table('store_targets')
    # ### end Alembic commands ###
