"""empty message

Revision ID: c070896d644a
Revises: a5d85bdc91e0
Create Date: 2026-09-23 11:12:36.205800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c070896d644a'
down_revision: Union[str, None] = 'a5d85bdc91e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'store_targets' not in existing_tables:
        op.create_table('store_targets',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('store_id', sa.Integer(), nullable=False),
            sa.Column('target_type', sa.String(length=30), nullable=False),
            sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
            sa.Column('period', sa.String(length=20), nullable=False),
            sa.Column('start_date', sa.DateTime(), nullable=False),
            sa.Column('end_date', sa.DateTime(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # Refresh existing tables and indexes
    existing_tables = set(inspector.get_table_names())
    def safe_create_index(table_name, index_name, columns, unique=False):
        if table_name in existing_tables:
            table_cols = {c['name'] for c in inspector.get_columns(table_name)}
            if not all(col in table_cols for col in columns):
                return
            idxs = {idx['name'] for idx in inspector.get_indexes(table_name)}
            if index_name not in idxs:
                op.create_index(index_name, table_name, columns, unique=unique)

    safe_create_index('store_targets', op.f('ix_store_targets_id'), ['id'])
    safe_create_index('store_targets', op.f('ix_store_targets_store_id'), ['store_id'])

    if 'delivery_methods' in existing_tables:
        op.alter_column('delivery_methods', 'updated_at',
                   existing_type=mysql.DATETIME(),
                   nullable=False)
    if 'delivery_zones' in existing_tables:
        op.alter_column('delivery_zones', 'updated_at',
                   existing_type=mysql.DATETIME(),
                   nullable=False)

    safe_create_index('payment_gateways', op.f('ix_payment_gateways_status'), ['status'])
    safe_create_index('payment_splits', op.f('ix_payment_splits_transaction_id'), ['transaction_id'])
    safe_create_index('payment_webhook_logs', op.f('ix_payment_webhook_logs_status'), ['status'])
    safe_create_index('payment_webhook_logs', op.f('ix_payment_webhook_logs_transaction_id'), ['transaction_id'])

    if 'payments' in existing_tables:
        pay_cols = [c['name'] for c in inspector.get_columns('payments')]
        if 'gateway_response' in pay_cols:
            op.alter_column('payments', 'gateway_response',
                       existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
                       type_=sa.Text(),
                       existing_nullable=True)
    safe_create_index('payments', op.f('ix_payments_status'), ['status'])
    safe_create_index('payments', op.f('ix_payments_transaction_id'), ['transaction_id'])

    if 'products' in existing_tables:
        prod_cols = [c['name'] for c in inspector.get_columns('products')]
        if 'mrp' in prod_cols:
            op.alter_column('products', 'mrp',
                       existing_type=mysql.DECIMAL(precision=12, scale=2),
                       nullable=False,
                       existing_server_default=sa.text("'0.00'"))

    if 'refunds' in existing_tables:
        ref_cols = [c['name'] for c in inspector.get_columns('refunds')]
        if 'refund_status' in ref_cols:
            op.alter_column('refunds', 'refund_status',
                       existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
                       type_=sa.String(length=20),
                       existing_nullable=True)

    safe_create_index('settlements', op.f('ix_settlements_gateway_id'), ['gateway_id'])
    safe_create_index('settlements', op.f('ix_settlements_status'), ['status'])
    safe_create_index('store_expenses', op.f('ix_store_expenses_id'), ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_expenses_id'), table_name='store_expenses')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_gateway_id'), table_name='settlements')
    op.alter_column('refunds', 'refund_status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)
    op.alter_column('products', 'mrp',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.alter_column('payments', 'gateway_response',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_webhook_logs_transaction_id'), table_name='payment_webhook_logs')
    op.drop_index(op.f('ix_payment_webhook_logs_status'), table_name='payment_webhook_logs')
    op.drop_index(op.f('ix_payment_splits_transaction_id'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_gateways_status'), table_name='payment_gateways')
    op.alter_column('delivery_zones', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('delivery_methods', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_store_targets_store_id'), table_name='store_targets')
    op.drop_index(op.f('ix_store_targets_id'), table_name='store_targets')
    op.drop_table('store_targets')
    # ### end Alembic commands ###
