"""add password reset tokens

Revision ID: eb1d473977a5
Revises: 349e9237cc4e
Create Date: 2026-08-13 16:40:02.226767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1d473977a5'
down_revision: Union[str, None] = '349e9237cc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gstin', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_column('customers', 'gstin')
    # ### end Alembic commands ###